FROM node:12.19.0-buster as build

RUN mkdir /usr/app
WORKDIR /usr/app

COPY package.json /usr/app
COPY package-lock.json /usr/app
RUN npm install --silent

COPY . /usr/app

RUN npm run build

FROM nginx:1.19.3-alpine
COPY --from=build /usr/app/build /usr/share/nginx/html
COPY nginx/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]

